### ISSUE TITLE
XHTML compatibility

### ISSUE THREAD

**Issue by chinoto** [DHTMLX/scheduler#20]
I use XHTML for testing and this breaks under XHTML, fortunately it isn't too hard of a fix. XHTML is case sensitive and only defines a few named entities so createElement() should be given a lowercase string and characters should be escaped using code points (&amp;nbsp; vs &amp;#xa0; and &amp;ndash; vs &amp;#x2013;). There are also a few places where an entity was missing a semicolon, which is also invalid.

I believe this commit has all the changes necessary for scheduler to not break in XHTML mode, so it can be used for reference if needed: https://github.com/chinoto/scheduler/commit/c7428b9699459fe7a3b13ec9159c6050967f7769

**Comment by AlexKlimenkov** [comment]
Hello,
thanks for contributing. We'll review changes and if all good, merge them into the dev repository so they go to future versions of the scheduler (this repository will be updated on the next minor update of the scheduler).
Please note that while your update brings XHTML compatibility, there is no guarantee on how long component will stay XHTLM compatible since currently we don't do any tests for that - so somebody could break it without realizing it.

>>characters should be escaped using code points (&nbsp; vs &#xa0; and &ndash; vs &#x2013;)

Could you please refer where I can read about it?
I haven't exactly digged into W3C xhtml specs, but the online validator https://validator.w3.org/check seems to me ok with named escape characters (e.g. &nbsp) both in XHTML 1.1 and XHTML 1.0 document modes.

**Comment by chinoto** [comment]
Odd, perhaps there is something I am unaware of that declares those entities or maybe the validator doesn't check that. As for the scheduler breaking XHTML compatibility again, no problem, as long as most of the stuff is fixed that I found, I can easily fix any new issues that arise when I update and submit the fixes for those too.
Here are some links to info about entities:
[List of predefined XML entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML)
[Entity Declarations](https://en.wikipedia.org/wiki/Document_type_definition#Entity_declarations)
[Some guide about character escapes](https://www.w3.org/International/questions/qa-escapes)

**Comment by AlexKlimenkov** [comment]
I'm closing the issue and a pull request as changes are merged into the current version of the scheduler. This repository will be updated with the next release of dhtmlxScheduler (probably early-mid March 2018)
