### ISSUE TITLE
Heavy misalignment header, rest of grid

### ISSUE THREAD

**Issue by sergionegri** [DHTMLX/scheduler#32]
Please check the demo here: https://docs.dhtmlx.com/scheduler/samples/06_timeline/13_full_month_scale.html

This is what I see:
<img width="958" alt="misalignment" src="https://user-images.githubusercontent.com/10323575/29029686-d31c74b8-7b88-11e7-95fb-48e36037377b.png">

Windows 10.
Chrome 59.0.3071.115 64 bit
Only minor misalignment on IE 11.

**Comment by AlexKlimenkov** [comment]
Hi,
do you use high dpi display (e.g. 2k, 4k)?
Everything looks ok for me locally on 1080p display, however, some misalignments are expected when the browser is zoomed. 
Since I can see no zoom icon on your screenshot - probably the issue can be also caused by system scaling and devicePixelRatio of the display you use. Please clarify what device do you use so we'd know where to look.

**Comment by sergionegri** [comment]
I have a screen with resolution 1920x1080, pretty standard. No zooming.

Here's the main display page:
[image: Inline image 1]

**Comment by AlexKlimenkov** [comment]
I'm closing the issue due to inactivity.
We haven't found a way to reproduce it so far. If there is a way to reliably reproduce the issue, e.g. maybe there are some browser or OS settings that trigger the misalignment - please feel free to reopen

**Comment by Wiseman19x** [comment]
Its happening because of the recommended windows resolution setting under Scale and Layout in the display settings. Machines over 100% get this miss alignment. I can't seem to fix it just looking to see if anyone has a solution .
